apiVersion: v1
kind: Pod
metadata:
  name: pvc-extractor
  namespace: vllm-test
spec:
  restartPolicy: Never
  containers:
    - name: extractor-container
      image: busybox:latest
      command: ["sleep", "3600"]
      volumeMounts:
        - name: results-storage
          mountPath: "/mnt/pvc"
  volumes:
    - name: results-storage
      persistentVolumeClaim:
        claimName: guidellm-results-pvc
